### ISSUE TITLE
Suggestion - Allow setting tile-level base URLs and headers

### ISSUE THREAD

**Issue by DJXJD** [kennedn/Stateful#16]
Hi there! Absolutely loving the new app!

A feature that I believe would help significantly in my use-case would be the ability to set a base URL, and base headers, at a tile level. For someone who is using the app to interface with multiple different services (1 independent service per tile), oftentimes running on different devices, having those tile-level base URLs and headers would be a godsend.

The thought of the added convenience of being able to change 1 base URL (and maybe some base headers) to redirect a tile's functionality, as opposed to 1 URL (and maybe some headers) for each button, has me looking even more forward to taking advantage of all the cool things that this app makes possible!

**Comment by kennedn** [comment]
Hi,

I am glad someone is getting some use out of it other than me :). Your request is quite reasonable, I will take a look at this for the next release.

Cheers,

**Comment by kennedn** [comment]
Implemented in [v1.3](https://github.com/kennedn/Stateful/releases/tag/v1.3)
