### ISSUE TITLE
Does it work with Gadgetbridg?

### ISSUE THREAD

**Issue by Mannshoch** [kennedn/Stateful#23]
Does it work with Gadgetbridg? how could I configure it if it does?

**Comment by kennedn** [comment]
I have never used GadgetBridge but from the looks of it, it only has very rudimentary support for app configuration. 

Stateful uses a custom Clay implementation and sends compressed LZstring URLs backwards and forwards between the Webview and Pebblekit JS, so I suspect that GadgetBridge will never support app configuration in Stateful.

You will need to use the official pebble app with Rebble Web Services ([See here for how to](https://help.rebble.io/setup/)) if you want to use Stateful.
